// Code generated by protoc-gen-go. DO NOT EDIT.
// source: book/book.proto

package book

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	author "github.com/ysugimoto/grpc-graphql-gateway/examples/basic/app/author"
	_ "github.com/ysugimoto/grpc-graphql-gateway/graphql"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BookType int32

const (
	BookType_JAVASCRIPT  BookType = 0
	BookType_ECMASCRIPT  BookType = 1
	BookType_GIT         BookType = 2
	BookType_ASP_DOT_NET BookType = 3
)

var BookType_name = map[int32]string{
	0: "JAVASCRIPT",
	1: "ECMASCRIPT",
	2: "GIT",
	3: "ASP_DOT_NET",
}

var BookType_value = map[string]int32{
	"JAVASCRIPT":  0,
	"ECMASCRIPT":  1,
	"GIT":         2,
	"ASP_DOT_NET": 3,
}

func (x BookType) String() string {
	return proto.EnumName(BookType_name, int32(x))
}

func (BookType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{0}
}

type Book struct {
	Id                   int64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string         `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Type                 BookType       `protobuf:"varint,3,opt,name=type,proto3,enum=book.BookType" json:"type,omitempty"`
	Author               *author.Author `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{0}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Book) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Book) GetType() BookType {
	if m != nil {
		return m.Type
	}
	return BookType_JAVASCRIPT
}

func (m *Book) GetAuthor() *author.Author {
	if m != nil {
		return m.Author
	}
	return nil
}

type ListBooksRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBooksRequest) Reset()         { *m = ListBooksRequest{} }
func (m *ListBooksRequest) String() string { return proto.CompactTextString(m) }
func (*ListBooksRequest) ProtoMessage()    {}
func (*ListBooksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{1}
}

func (m *ListBooksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBooksRequest.Unmarshal(m, b)
}
func (m *ListBooksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBooksRequest.Marshal(b, m, deterministic)
}
func (m *ListBooksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBooksRequest.Merge(m, src)
}
func (m *ListBooksRequest) XXX_Size() int {
	return xxx_messageInfo_ListBooksRequest.Size(m)
}
func (m *ListBooksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBooksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBooksRequest proto.InternalMessageInfo

type ListBooksResponse struct {
	Books                []*Book  `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBooksResponse) Reset()         { *m = ListBooksResponse{} }
func (m *ListBooksResponse) String() string { return proto.CompactTextString(m) }
func (*ListBooksResponse) ProtoMessage()    {}
func (*ListBooksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{2}
}

func (m *ListBooksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBooksResponse.Unmarshal(m, b)
}
func (m *ListBooksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBooksResponse.Marshal(b, m, deterministic)
}
func (m *ListBooksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBooksResponse.Merge(m, src)
}
func (m *ListBooksResponse) XXX_Size() int {
	return xxx_messageInfo_ListBooksResponse.Size(m)
}
func (m *ListBooksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBooksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBooksResponse proto.InternalMessageInfo

func (m *ListBooksResponse) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

type GetBookRequest struct {
	// this is example comment for id field
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookRequest) Reset()         { *m = GetBookRequest{} }
func (m *GetBookRequest) String() string { return proto.CompactTextString(m) }
func (*GetBookRequest) ProtoMessage()    {}
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{3}
}

func (m *GetBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookRequest.Unmarshal(m, b)
}
func (m *GetBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookRequest.Marshal(b, m, deterministic)
}
func (m *GetBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookRequest.Merge(m, src)
}
func (m *GetBookRequest) XXX_Size() int {
	return xxx_messageInfo_GetBookRequest.Size(m)
}
func (m *GetBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookRequest proto.InternalMessageInfo

func (m *GetBookRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreateBookRequest struct {
	Title                string         `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Type                 BookType       `protobuf:"varint,2,opt,name=type,proto3,enum=book.BookType" json:"type,omitempty"`
	Author               *author.Author `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateBookRequest) Reset()         { *m = CreateBookRequest{} }
func (m *CreateBookRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBookRequest) ProtoMessage()    {}
func (*CreateBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{4}
}

func (m *CreateBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBookRequest.Unmarshal(m, b)
}
func (m *CreateBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBookRequest.Marshal(b, m, deterministic)
}
func (m *CreateBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBookRequest.Merge(m, src)
}
func (m *CreateBookRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBookRequest.Size(m)
}
func (m *CreateBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBookRequest proto.InternalMessageInfo

func (m *CreateBookRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateBookRequest) GetType() BookType {
	if m != nil {
		return m.Type
	}
	return BookType_JAVASCRIPT
}

func (m *CreateBookRequest) GetAuthor() *author.Author {
	if m != nil {
		return m.Author
	}
	return nil
}

func init() {
	proto.RegisterEnum("book.BookType", BookType_name, BookType_value)
	proto.RegisterType((*Book)(nil), "book.Book")
	proto.RegisterType((*ListBooksRequest)(nil), "book.ListBooksRequest")
	proto.RegisterType((*ListBooksResponse)(nil), "book.ListBooksResponse")
	proto.RegisterType((*GetBookRequest)(nil), "book.GetBookRequest")
	proto.RegisterType((*CreateBookRequest)(nil), "book.CreateBookRequest")
}

func init() { proto.RegisterFile("book/book.proto", fileDescriptor_ee9082fb44230b1b) }

var fileDescriptor_ee9082fb44230b1b = []byte{
	// 479 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4f, 0x4f, 0xdb, 0x4e,
	0x10, 0xfd, 0xad, 0x9d, 0x3f, 0x30, 0x96, 0x8c, 0xd9, 0x5f, 0xa0, 0x5b, 0x9f, 0x2c, 0x1f, 0x2a,
	0xab, 0x12, 0x31, 0x4a, 0x55, 0x15, 0xf5, 0x66, 0x02, 0x42, 0x54, 0xb4, 0x45, 0x8e, 0xc5, 0xa1,
	0x17, 0xe4, 0x98, 0x95, 0x63, 0xe1, 0xb0, 0x8b, 0x77, 0xdd, 0x92, 0x7b, 0x4f, 0x39, 0xf6, 0xbb,
	0xe4, 0xfb, 0x55, 0xde, 0x35, 0x10, 0xa0, 0xaa, 0x7a, 0xf1, 0x78, 0x66, 0xf6, 0xed, 0x9b, 0xf7,
	0x34, 0x0b, 0x5b, 0x53, 0xc6, 0xae, 0xc3, 0xe6, 0x33, 0xe4, 0x15, 0x93, 0x0c, 0x77, 0x9a, 0x7f,
	0xf7, 0xff, 0xb4, 0x96, 0x33, 0x56, 0x85, 0x3a, 0xe8, 0x96, 0xbb, 0x93, 0x57, 0x29, 0x9f, 0xdd,
	0x96, 0x61, 0x1b, 0x75, 0xd9, 0xbf, 0x83, 0xce, 0x21, 0x63, 0xd7, 0xd8, 0x06, 0xa3, 0xb8, 0x22,
	0xc8, 0x43, 0x81, 0x19, 0x1b, 0xc5, 0x15, 0x1e, 0x40, 0x57, 0x16, 0xb2, 0xa4, 0xc4, 0xf0, 0x50,
	0xb0, 0x19, 0xeb, 0x04, 0xfb, 0xd0, 0x91, 0x0b, 0x4e, 0x89, 0xe9, 0xa1, 0xc0, 0x1e, 0xd9, 0x43,
	0x45, 0xdd, 0xe0, 0x93, 0x05, 0xa7, 0xb1, 0xea, 0xe1, 0x37, 0xd0, 0xd3, 0xc4, 0xa4, 0xe3, 0xa1,
	0xc0, 0x1a, 0xd9, 0xc3, 0x76, 0x8e, 0x48, 0x85, 0xb8, 0xed, 0xfa, 0x18, 0x9c, 0xb3, 0x42, 0xc8,
	0x06, 0x2d, 0x62, 0x7a, 0x5b, 0x53, 0x21, 0xfd, 0xf7, 0xb0, 0xbd, 0x56, 0x13, 0x9c, 0xdd, 0x08,
	0x8a, 0x3d, 0xe8, 0x36, 0x3c, 0x82, 0x20, 0xcf, 0x0c, 0xac, 0x11, 0x3c, 0xb2, 0xc6, 0xba, 0xe1,
	0x7b, 0x60, 0x9f, 0x50, 0x85, 0x6a, 0x2f, 0x7a, 0x2e, 0xc7, 0xaf, 0x61, 0x7b, 0x5c, 0xd1, 0x54,
	0xd2, 0xf5, 0x43, 0x0f, 0x1a, 0xd1, 0x9f, 0x34, 0x1a, 0xff, 0xa4, 0xd1, 0xfc, 0x9b, 0xc6, 0xb7,
	0x47, 0xb0, 0x71, 0x8f, 0xc4, 0x36, 0xc0, 0xa7, 0xe8, 0x22, 0x9a, 0x8c, 0xe3, 0xd3, 0xf3, 0xc4,
	0xf9, 0xaf, 0xc9, 0x8f, 0xc7, 0x9f, 0xef, 0x73, 0x84, 0xfb, 0x60, 0x9e, 0x9c, 0x26, 0x8e, 0x81,
	0xb7, 0xc0, 0x8a, 0x26, 0xe7, 0x97, 0x47, 0x5f, 0x93, 0xcb, 0x2f, 0xc7, 0x89, 0x63, 0x8e, 0x7e,
	0x1a, 0x60, 0x35, 0xd7, 0x4c, 0x68, 0xf5, 0xbd, 0xc8, 0x28, 0xbe, 0x80, 0xcd, 0x07, 0x97, 0xf0,
	0xae, 0x1e, 0xf0, 0xb9, 0x95, 0xee, 0xab, 0x17, 0x75, 0x6d, 0xa7, 0x4f, 0x96, 0x2b, 0x32, 0x68,
	0x2d, 0xf5, 0xad, 0x0d, 0xe4, 0x20, 0x57, 0x27, 0xf8, 0x03, 0xf4, 0x5b, 0x1b, 0xf1, 0x40, 0xa3,
	0x9f, 0xba, 0xea, 0xae, 0x59, 0xef, 0xc3, 0x72, 0x45, 0x7a, 0xa0, 0x16, 0x0e, 0x9f, 0x01, 0x3c,
	0xba, 0x8b, 0x5b, 0xe6, 0x17, 0x7e, 0x3f, 0x81, 0xbf, 0xfe, 0xb5, 0x22, 0x3b, 0x00, 0x99, 0x3a,
	0xa4, 0xb6, 0xb6, 0x0f, 0xdd, 0xe2, 0x86, 0xd7, 0xd2, 0xdd, 0x5d, 0xae, 0x08, 0x06, 0xbb, 0x64,
	0x59, 0x5a, 0xce, 0x98, 0x90, 0x1f, 0x0f, 0xf6, 0x0f, 0xf6, 0x1d, 0x74, 0x38, 0xfe, 0x16, 0xe5,
	0x85, 0x9c, 0xd5, 0xd3, 0x61, 0xc6, 0xe6, 0xe1, 0x42, 0xd4, 0x79, 0x31, 0x67, 0x92, 0x85, 0x79,
	0xc5, 0xb3, 0xbd, 0x76, 0xab, 0xf7, 0xf2, 0x54, 0xd2, 0x1f, 0xe9, 0x22, 0xa4, 0x77, 0xe9, 0x9c,
	0x97, 0x54, 0x84, 0xd3, 0x54, 0x14, 0x59, 0x98, 0x72, 0xae, 0xde, 0xc9, 0xb4, 0xa7, 0xd6, 0xfe,
	0xdd, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9d, 0xa1, 0x34, 0xd2, 0x3b, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BookServiceClient is the client API for BookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookServiceClient interface {
	ListBooks(ctx context.Context, in *ListBooksRequest, opts ...grpc.CallOption) (*ListBooksResponse, error)
	GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*Book, error)
	CreateBook(ctx context.Context, in *CreateBookRequest, opts ...grpc.CallOption) (*Book, error)
}

type bookServiceClient struct {
	cc *grpc.ClientConn
}

func NewBookServiceClient(cc *grpc.ClientConn) BookServiceClient {
	return &bookServiceClient{cc}
}

func (c *bookServiceClient) ListBooks(ctx context.Context, in *ListBooksRequest, opts ...grpc.CallOption) (*ListBooksResponse, error) {
	out := new(ListBooksResponse)
	err := c.cc.Invoke(ctx, "/book.BookService/ListBooks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*Book, error) {
	out := new(Book)
	err := c.cc.Invoke(ctx, "/book.BookService/GetBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) CreateBook(ctx context.Context, in *CreateBookRequest, opts ...grpc.CallOption) (*Book, error) {
	out := new(Book)
	err := c.cc.Invoke(ctx, "/book.BookService/CreateBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookServiceServer is the server API for BookService service.
type BookServiceServer interface {
	ListBooks(context.Context, *ListBooksRequest) (*ListBooksResponse, error)
	GetBook(context.Context, *GetBookRequest) (*Book, error)
	CreateBook(context.Context, *CreateBookRequest) (*Book, error)
}

// UnimplementedBookServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBookServiceServer struct {
}

func (*UnimplementedBookServiceServer) ListBooks(ctx context.Context, req *ListBooksRequest) (*ListBooksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBooks not implemented")
}
func (*UnimplementedBookServiceServer) GetBook(ctx context.Context, req *GetBookRequest) (*Book, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBook not implemented")
}
func (*UnimplementedBookServiceServer) CreateBook(ctx context.Context, req *CreateBookRequest) (*Book, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBook not implemented")
}

func RegisterBookServiceServer(s *grpc.Server, srv BookServiceServer) {
	s.RegisterService(&_BookService_serviceDesc, srv)
}

func _BookService_ListBooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).ListBooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/book.BookService/ListBooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).ListBooks(ctx, req.(*ListBooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_GetBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).GetBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/book.BookService/GetBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).GetBook(ctx, req.(*GetBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_CreateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).CreateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/book.BookService/CreateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).CreateBook(ctx, req.(*CreateBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BookService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "book.BookService",
	HandlerType: (*BookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBooks",
			Handler:    _BookService_ListBooks_Handler,
		},
		{
			MethodName: "GetBook",
			Handler:    _BookService_GetBook_Handler,
		},
		{
			MethodName: "CreateBook",
			Handler:    _BookService_CreateBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "book/book.proto",
}
