// Code generated by protoc-gen-go. DO NOT EDIT.
// source: graphql.proto

package graphql

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GraphqlResponse struct {
	Repeated             bool     `protobuf:"varint,1,opt,name=repeated,proto3" json:"repeated,omitempty"`
	Optional             bool     `protobuf:"varint,2,opt,name=optional,proto3" json:"optional,omitempty"`
	Expose               string   `protobuf:"bytes,3,opt,name=expose,proto3" json:"expose,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GraphqlResponse) Reset()         { *m = GraphqlResponse{} }
func (m *GraphqlResponse) String() string { return proto.CompactTextString(m) }
func (*GraphqlResponse) ProtoMessage()    {}
func (*GraphqlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ce0fc368bdc1a51, []int{0}
}

func (m *GraphqlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphqlResponse.Unmarshal(m, b)
}
func (m *GraphqlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphqlResponse.Marshal(b, m, deterministic)
}
func (m *GraphqlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphqlResponse.Merge(m, src)
}
func (m *GraphqlResponse) XXX_Size() int {
	return xxx_messageInfo_GraphqlResponse.Size(m)
}
func (m *GraphqlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphqlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GraphqlResponse proto.InternalMessageInfo

func (m *GraphqlResponse) GetRepeated() bool {
	if m != nil {
		return m.Repeated
	}
	return false
}

func (m *GraphqlResponse) GetOptional() bool {
	if m != nil {
		return m.Optional
	}
	return false
}

func (m *GraphqlResponse) GetExpose() string {
	if m != nil {
		return m.Expose
	}
	return ""
}

type GraphqlQuery struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Field                string           `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	Autoresolve          bool             `protobuf:"varint,3,opt,name=autoresolve,proto3" json:"autoresolve,omitempty"`
	Response             *GraphqlResponse `protobuf:"bytes,4,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GraphqlQuery) Reset()         { *m = GraphqlQuery{} }
func (m *GraphqlQuery) String() string { return proto.CompactTextString(m) }
func (*GraphqlQuery) ProtoMessage()    {}
func (*GraphqlQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ce0fc368bdc1a51, []int{1}
}

func (m *GraphqlQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphqlQuery.Unmarshal(m, b)
}
func (m *GraphqlQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphqlQuery.Marshal(b, m, deterministic)
}
func (m *GraphqlQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphqlQuery.Merge(m, src)
}
func (m *GraphqlQuery) XXX_Size() int {
	return xxx_messageInfo_GraphqlQuery.Size(m)
}
func (m *GraphqlQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphqlQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GraphqlQuery proto.InternalMessageInfo

func (m *GraphqlQuery) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GraphqlQuery) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *GraphqlQuery) GetAutoresolve() bool {
	if m != nil {
		return m.Autoresolve
	}
	return false
}

func (m *GraphqlQuery) GetResponse() *GraphqlResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

type GraphqlMutation struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Field                string           `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	Autoresolve          bool             `protobuf:"varint,3,opt,name=autoresolve,proto3" json:"autoresolve,omitempty"`
	InputType            bool             `protobuf:"varint,4,opt,name=input_type,json=inputType,proto3" json:"input_type,omitempty"`
	Response             *GraphqlResponse `protobuf:"bytes,5,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GraphqlMutation) Reset()         { *m = GraphqlMutation{} }
func (m *GraphqlMutation) String() string { return proto.CompactTextString(m) }
func (*GraphqlMutation) ProtoMessage()    {}
func (*GraphqlMutation) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ce0fc368bdc1a51, []int{2}
}

func (m *GraphqlMutation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphqlMutation.Unmarshal(m, b)
}
func (m *GraphqlMutation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphqlMutation.Marshal(b, m, deterministic)
}
func (m *GraphqlMutation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphqlMutation.Merge(m, src)
}
func (m *GraphqlMutation) XXX_Size() int {
	return xxx_messageInfo_GraphqlMutation.Size(m)
}
func (m *GraphqlMutation) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphqlMutation.DiscardUnknown(m)
}

var xxx_messageInfo_GraphqlMutation proto.InternalMessageInfo

func (m *GraphqlMutation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GraphqlMutation) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *GraphqlMutation) GetAutoresolve() bool {
	if m != nil {
		return m.Autoresolve
	}
	return false
}

func (m *GraphqlMutation) GetInputType() bool {
	if m != nil {
		return m.InputType
	}
	return false
}

func (m *GraphqlMutation) GetResponse() *GraphqlResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

type GraphqlField struct {
	Optional             bool     `protobuf:"varint,1,opt,name=optional,proto3" json:"optional,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GraphqlField) Reset()         { *m = GraphqlField{} }
func (m *GraphqlField) String() string { return proto.CompactTextString(m) }
func (*GraphqlField) ProtoMessage()    {}
func (*GraphqlField) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ce0fc368bdc1a51, []int{3}
}

func (m *GraphqlField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphqlField.Unmarshal(m, b)
}
func (m *GraphqlField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphqlField.Marshal(b, m, deterministic)
}
func (m *GraphqlField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphqlField.Merge(m, src)
}
func (m *GraphqlField) XXX_Size() int {
	return xxx_messageInfo_GraphqlField.Size(m)
}
func (m *GraphqlField) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphqlField.DiscardUnknown(m)
}

var xxx_messageInfo_GraphqlField proto.InternalMessageInfo

func (m *GraphqlField) GetOptional() bool {
	if m != nil {
		return m.Optional
	}
	return false
}

func (m *GraphqlField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

var E_Query = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*GraphqlQuery)(nil),
	Field:         50001,
	Name:          "graphql.query",
	Tag:           "bytes,50001,opt,name=query",
	Filename:      "graphql.proto",
}

var E_Mutation = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*GraphqlMutation)(nil),
	Field:         50002,
	Name:          "graphql.mutation",
	Tag:           "bytes,50002,opt,name=mutation",
	Filename:      "graphql.proto",
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*GraphqlField)(nil),
	Field:         50003,
	Name:          "graphql.field",
	Tag:           "bytes,50003,opt,name=field",
	Filename:      "graphql.proto",
}

func init() {
	proto.RegisterType((*GraphqlResponse)(nil), "graphql.GraphqlResponse")
	proto.RegisterType((*GraphqlQuery)(nil), "graphql.GraphqlQuery")
	proto.RegisterType((*GraphqlMutation)(nil), "graphql.GraphqlMutation")
	proto.RegisterType((*GraphqlField)(nil), "graphql.GraphqlField")
	proto.RegisterExtension(E_Query)
	proto.RegisterExtension(E_Mutation)
	proto.RegisterExtension(E_Field)
}

func init() { proto.RegisterFile("graphql.proto", fileDescriptor_3ce0fc368bdc1a51) }

var fileDescriptor_3ce0fc368bdc1a51 = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0xd9, 0xfe, 0x33, 0xd9, 0x2a, 0xc2, 0xa2, 0x12, 0x0a, 0x95, 0xd0, 0x53, 0x4f, 0x29,
	0xa8, 0xa7, 0x1e, 0x3c, 0xea, 0xc5, 0x22, 0x2e, 0xe2, 0x55, 0xb6, 0x66, 0xda, 0x06, 0xd2, 0xec,
	0x76, 0xb3, 0x11, 0xfb, 0x02, 0x9e, 0x7d, 0x16, 0xdf, 0x44, 0x7d, 0x21, 0xe9, 0x6c, 0x36, 0xd6,
	0x16, 0xd1, 0x83, 0xb7, 0xcc, 0xec, 0xec, 0x97, 0xdf, 0xf7, 0xcd, 0xd2, 0xbd, 0xa9, 0x16, 0x6a,
	0xb6, 0x48, 0x23, 0xa5, 0xa5, 0x91, 0x6c, 0xa7, 0x2c, 0x3b, 0xe1, 0x54, 0xca, 0x69, 0x0a, 0x03,
	0x6c, 0x8f, 0x8b, 0xc9, 0x20, 0x86, 0xfc, 0x41, 0x27, 0xca, 0x48, 0x6d, 0x47, 0x7b, 0x82, 0xee,
	0x5f, 0xda, 0x61, 0x0e, 0xb9, 0x92, 0x59, 0x0e, 0xac, 0x43, 0x3d, 0x0d, 0x0a, 0x84, 0x81, 0x38,
	0x20, 0x21, 0xe9, 0x7b, 0xbc, 0xaa, 0x57, 0x67, 0x52, 0x99, 0x44, 0x66, 0x22, 0x0d, 0x6a, 0xf6,
	0xcc, 0xd5, 0xec, 0x88, 0xb6, 0xe0, 0x49, 0xc9, 0x1c, 0x82, 0x7a, 0x48, 0xfa, 0x3e, 0x2f, 0xab,
	0xde, 0x0b, 0xa1, 0xbb, 0xe5, 0x3f, 0x6e, 0x0a, 0xd0, 0x4b, 0xc6, 0x68, 0x23, 0x13, 0x73, 0x40,
	0x71, 0x9f, 0xe3, 0x37, 0x3b, 0xa0, 0xcd, 0x49, 0x02, 0x69, 0x8c, 0xaa, 0x3e, 0xb7, 0x05, 0x0b,
	0x69, 0x5b, 0x14, 0x46, 0x6a, 0xc8, 0x65, 0xfa, 0x68, 0x75, 0x3d, 0xbe, 0xde, 0x62, 0x67, 0x2b,
	0x58, 0x0b, 0x1e, 0x34, 0x42, 0xd2, 0x6f, 0x9f, 0x04, 0x91, 0x0b, 0x63, 0xc3, 0x18, 0xaf, 0x26,
	0x7b, 0xaf, 0xa4, 0xb2, 0x3d, 0x2a, 0x8c, 0x58, 0x19, 0xf8, 0x57, 0xaa, 0x2e, 0xa5, 0x49, 0xa6,
	0x0a, 0x73, 0x6f, 0x96, 0xca, 0x72, 0x79, 0xdc, 0xc7, 0xce, 0xed, 0x52, 0x7d, 0x87, 0x6e, 0xfe,
	0x19, 0xfa, 0xbc, 0x8a, 0xf1, 0x02, 0x31, 0xd6, 0x77, 0x41, 0x36, 0x76, 0xe1, 0xcc, 0xd4, 0xbe,
	0xcc, 0x0c, 0x47, 0xb4, 0xb9, 0xc0, 0xfc, 0x8f, 0x23, 0xfb, 0x2c, 0x22, 0xf7, 0x2c, 0xa2, 0x11,
	0x98, 0x99, 0x8c, 0xaf, 0xf1, 0x76, 0x1e, 0xbc, 0x3d, 0xd7, 0x11, 0xea, 0x70, 0x13, 0x0a, 0xd7,
	0xc7, 0xad, 0xca, 0xf0, 0x8e, 0x7a, 0x73, 0x97, 0xdd, 0x6f, 0x8a, 0xef, 0xa5, 0xe2, 0x96, 0x4d,
	0x97, 0x3e, 0xaf, 0xb4, 0x86, 0x57, 0x65, 0xe6, 0xac, 0xbb, 0x25, 0x8a, 0xbe, 0x9d, 0xe6, 0xc7,
	0x4f, 0x94, 0x38, 0x55, 0xee, 0x6a, 0xdc, 0xc2, 0xcb, 0xa7, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xfa, 0x05, 0x90, 0x68, 0x22, 0x03, 0x00, 0x00,
}
